### ISSUE TITLE
Add the START command

### ISSUE THREAD

**Issue by JohanCDev** [JohanCDev/Gomoku#1]
# Description of the command
Initializes brain and create an empty board, but doesn't make any move yet. The parameter is size of the board. 

# Format of the command
START [size] -> Only 20x20 is allowed on Epitech subject

# Possible answers
OK -> Everything is good
ERROR [message] -> Unsupported size or other error

**Comment by 31Nathan** [comment]
20x20 is required in tournament, but in every other format you choose
