### ISSUE TITLE
Add the ABOUT command

### ISSUE THREAD

**Issue by JohanCDev** [JohanCDev/Gomoku#7]
# Description of the command
The brain is expected to send some information about itself on one line. Each info must be written as keyword, equals sign, text value in quotation marks. Recommended keywords are name, version, author, country, www, email. Values should be separated by commas that can be followed by spaces. The manager can use this info, but must cope with old brains that used to send only human-readable text.

# Format of the command
ABOUT

# Possible answers
name="<brain_name>", version="<brain_version>", author="<brain_author>", country="<brain_nationality>"
ERROR [message]

**Comment by 31Nathan** [comment]
https://github.com/JohanCDev/Gomoku/pull/22
